# Generated by Django 6.1.1 on 2026-09-16 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document_filename', models.CharField(default='document.png', max_length=255)),
                ('document_type', models.CharField(default='Demo Identity Credential', max_length=100)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='LOW REVIEW', max_length=50)),
                ('image_quality_score', models.FloatField(default=100.0)),
                ('blur_detected', models.BooleanField(default=False)),
                ('extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_id', models.CharField(blank=True, max_length=100, null=True)),
                ('flags_count', models.IntegerField(default=0)),
                ('processing_time_ms', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
